# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=15)),
                ('ip_address', models.CharField(max_length=15)),
                ('state_code', models.CharField(max_length=3)),
                ('architecture', models.CharField(max_length=15)),
                ('monitored', models.BooleanField()),
                ('launched', models.DateTimeField()),
                ('placement', models.CharField(max_length=15)),
                ('private_dns', models.CharField(max_length=63)),
                ('public_dns', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('changes', models.CharField(max_length=1023)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.Instance')),
            ],
        ),
    ]
