# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20170706_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='ip_address',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
